extends: capitalization
message: "'%s' should be in title case"
level: error
scope: heading.h1
match: $title
style: AP
exceptions:
  - brew(1)
  - macOS
  - Homebrew/brew
  - Homebrew/homebrew-core
  - Homebrew/linuxbrew-core
  - Homebrew/homebrew-cask
  - (or Linux)
