apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: webapp
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/instance: styled-proverbs
    app.kubernetes.io/version: '0.0.0'
    app.kubernetes.io/component: function
    app.kubernetes.io/part-of: serverless
    app.kubernetes.io/managed-by: tilt

spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 31515
  selector:
    app: backend
