version: '3.9'

services:
  app:
    container_name: styled-proverbs
    hostname: '$APP_HOSTNAME'
    build:
      context: './'
      dockerfile: Dockerfile
    restart: always
    volumes:
      - type: volume
        source: appvolume
        target: /usr/src/app
        volume:
          nocopy: true
      - type: bind
        source: ./data
        target: /usr/src/data
    healthcheck:
      test: ['CMD-SHELL', 'nc', '-vz', 'localhost', '3000']
      interval: 3s
      retries: 15
      start_period: 30s
    networks:
      - default
    ports:
      - '${IP_ADDRESS:-127.0.0.1}:${APP_SERVER_PORT:-3000}:3000'
    deploy:
      mode: global
    logging:
      options:
        max-size: '100m'
        max-file: '10'

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450

volumes:
  appvolume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./
