/**
 * Profile
 * @desc Enumeration type representing supported profiles
 */
export enum Profile {
    dev = 'dev',
    prod = 'prod',
    test = 'test',
}

/**
 * HeroPattern
 * @desc Enumeration type representing supported background patterns
 */
export enum HeroPattern {
    jigsaw = 'jigsaw',
    overcast = 'overcast',
    formalInvitation = 'formalInvitation',
    topography = 'topography',
    texture = 'texture',
    jupiter = 'jupiter',
    architect = 'architect',
    cutout = 'cutout',
    hideout = 'hideout',
    graphPaper = 'graphPaper',
    yyy = 'yyy',
    squares = 'squares',
    fallingTriangles = 'fallingTriangles',
    pianoMan = 'pianoMan',
    pieFactory = 'pieFactory',
    dominos = 'dominos',
    hexagons = 'hexagons',
    charlieBrown = 'charlieBrown',
    autumn = 'autumn',
    temple = 'temple',
    stampCollection = 'stampCollection',
    deathStar = 'deathStar',
    churchOnSunday = 'churchOnSunday',
    iLikeFood = 'iLikeFood',
    overlappingHexagons = 'overlappingHexagons',
    bamboo = 'bamboo',
    bathroomFloor = 'bathroomFloor',
    corkScrew = 'corkScrew',
    happyIntersection = 'happyIntersection',
    kiwi = 'kiwi',
    lips = 'lips',
    lisbon = 'lisbon',
    randomShapes = 'randomShapes',
    steelBeams = 'steelBeams',
    tinyCheckers = 'tinyCheckers',
    xEquals = 'xEquals',
    anchorsAway = 'anchorsAway',
    bevelCircle = 'bevelCircle',
    brickWall = 'brickWall',
    fancyRectangles = 'fancyRectangles',
    heavyRain = 'heavyRain',
    overlappingCircles = 'overlappingCircles',
    plus = 'plus',
    roundedPlusConnected = 'roundedPlusConnected',
    volcanoLamp = 'volcanoLamp',
    wiggle = 'wiggle',
    bubbles = 'bubbles',
    cage = 'cage',
    connections = 'connections',
    current = 'current',
    diagonalStripes = 'diagonalStripes',
    flippedDiamonds = 'flippedDiamonds',
    floatingCogs = 'floatingCogs',
    glamorous = 'glamorous',
    leaf = 'leaf',
    linesInMotion = 'linesInMotion',
    moroccan = 'moroccan',
    morphingDiamonds = 'morphingDiamonds',
    rails = 'rails',
    rain = 'rain',
    skulls = 'skulls',
    squaresInSquares = 'squaresInSquares',
    stripes = 'stripes',
    ticTacToe = 'ticTacToe',
    zigZag = 'zigZag',
    aztec = 'aztec',
    bankNote = 'bankNote',
    boxes = 'boxes',
    circlesAndSquares = 'circlesAndSquares',
    circuitBoard = 'circuitBoard',
    curtain = 'curtain',
    diagonalLines = 'diagonalLines',
    endlessClouds = 'endlessClouds',
    eyes = 'eyes',
    floorTile = 'floorTile',
    groovy = 'groovy',
    intersectingCircles = 'intersectingCircles',
    melt = 'melt',
    overlappingDiamonds = 'overlappingDiamonds',
    parkayFloor = 'parkayFloor',
    pixelDots = 'pixelDots',
    polkaDots = 'polkaDots',
    signal = 'signal',
    slantedStars = 'slantedStars',
    wallpaper = 'wallpaper',
}

/**
 * LanguagePattern
 * @desc Enumeration type representing supported language patterns
 */
export enum LanguagePattern {
    english = 'english',
    eritrean = 'eritrean',
    eskimo = 'eskimo',
    canadian = 'canadian',
    canary_islander = 'canary_islander',
    cape_verdean = 'cape_verdean',
    catalan = 'catalan',
    venezuelan = 'venezuelan',
    american = 'american',
    belgian = 'belgian',
    bambara = 'bambara',
    guinean = 'guinean',
    somali = 'somali',
    korean = 'korean',
    albanian = 'albanian',
    mauritian = 'mauritian',
    czechoslovakian = 'czechoslovakian',
    antillean = 'antillean',
    zambian = 'zambian',
    west_african = 'west_african',
    virgin_islander = 'virgin_islander',
    french_guianese = 'french_guianese',
    anii = 'anii',
    bible = 'bible',
    kikuyu = 'kikuyu',
    klingon = 'klingon',
    koran = 'koran',
    gambian = 'gambian',
    flemish = 'flemish',
    malay = 'malay',
    goan = 'goan',
    byzantium = 'byzantium',
    kashmiri = 'kashmiri',
    latin_american = 'latin_american',
    azerbaijani = 'azerbaijani',
    sanskrit = 'sanskrit',
    costa_rikan = 'costa_rikan',
    spanish = 'spanish',
    danish = 'danish',
    darkovan = 'darkovan',
    dutch = 'dutch',
    zimbabwean = 'zimbabwean',
    peruvian = 'peruvian',
    surinamese = 'surinamese',
    gypsy = 'gypsy',
    polish = 'polish',
    persian = 'persian',
    nepalese = 'nepalese',
    puerto_rikan = 'puerto_rikan',
    sri_lankan = 'sri_lankan',
    trinidadian = 'trinidadian',
    burundian = 'burundian',
    beninese = 'beninese',
    bengali = 'bengali',
    colombian = 'colombian',
    ecuadorian = 'ecuadorian',
    panamanian = 'panamanian',
    paraguayan = 'paraguayan',
    guyanese = 'guyanese',
    burkinabe = 'burkinabe',
    angolan = 'angolan',
    south_african = 'south_african',
    basque = 'basque',
    dominican = 'dominican',
    nicaraguan = 'nicaraguan',
    martiniquais = 'martiniquais',
    jordanian = 'jordanian',
    tibetan = 'tibetan',
    tanzanian = 'tanzanian',
    cypriot = 'cypriot',
    walloon = 'walloon',
    babylonian = 'babylonian',
    haitian = 'haitian',
    algerian = 'algerian',
    myanmar = 'myanmar',
    swahili = 'swahili',
    iraqi = 'iraqi',
    romanian = 'romanian',
    serbian = 'serbian',
    bedouin = 'bedouin',
    ivorian = 'ivorian',
    yemeni = 'yemeni',
    russian = 'russian',
    scottish = 'scottish',
    arabian = 'arabian',
    andorran = 'andorran',
    belizean = 'belizean',
    indonesian = 'indonesian',
    jewish = 'jewish',
    senegalese = 'senegalese',
    islamic = 'islamic',
    israeli = 'israeli',
    french = 'french',
    fijian = 'fijian',
    croatian = 'croatian',
    kenyan = 'kenyan',
    malagasy = 'malagasy',
    latin = 'latin',
    moorish = 'moorish',
    swiss = 'swiss',
    turkish = 'turkish',
    ethiopian = 'ethiopian',
    faroese = 'faroese',
    malaysian = 'malaysian',
    malawian = 'malawian',
    ghanaian = 'ghanaian',
    maltese = 'maltese',
    maori = 'maori',
    filipino = 'filipino',
    mexican = 'mexican',
    congolese = 'congolese',
    german = 'german',
    afghan = 'afghan',
    african = 'african',
    cameroonian = 'cameroonian',
    iranian = 'iranian',
    icelandic = 'icelandic',
    swedish = 'swedish',
    mongolian = 'mongolian',
    ugandan = 'ugandan',
    uighur = 'uighur',
    lithuanian = 'lithuanian',
    italian = 'italian',
    irish = 'irish',
    egyptian = 'egyptian',
    hawaiian = 'hawaiian',
    cambodian = 'cambodian',
    bolivian = 'bolivian',
    creole = 'creole',
    cretian = 'cretian',
    zen = 'zen',
    sierra_leonean = 'sierra_leonean',
    singaporean = 'singaporean',
    sinhalese = 'sinhalese',
    kanuri = 'kanuri',
    argentinian = 'argentinian',
    japanese = 'japanese',
    armenian = 'armenian',
    ashanti = 'ashanti',
    yugoslavian = 'yugoslavian',
    zaire = 'zaire',
    yiddish = 'yiddish',
    thai = 'thai',
    burmese = 'burmese',
    greek = 'greek',
    guadeloupe = 'guadeloupe',
    new_zelander = 'new_zelander',
    cuban = 'cuban',
    palestinian = 'palestinian',
    welsh = 'welsh',
    zulu = 'zulu',
    bantu = 'bantu',
    jamaican = 'jamaican',
    georgian = 'georgian',
    tunisian = 'tunisian',
    slovakian = 'slovakian',
    togolese = 'togolese',
    tongan = 'tongan',
    breton = 'breton',
    bugundan = 'bugundan',
    estonian = 'estonian',
    latvian = 'latvian',
    gabonese = 'gabonese',
    sudanese = 'sudanese',
    sumerian = 'sumerian',
    moroccan = 'moroccan',
    vietnamese = 'vietnamese',
    indian = 'indian',
    hebrew = 'hebrew',
    czech = 'czech',
    nigerian = 'nigerian',
    brazilian = 'brazilian',
    rwandan = 'rwandan',
    salvadorian = 'salvadorian',
    chilean = 'chilean',
    namibian = 'namibian',
    austrian = 'austrian',
    zanzibar = 'zanzibar',
    taiwanese = 'taiwanese',
    chadian = 'chadian',
    syrian = 'syrian',
    tahitian = 'tahitian',
    bosnian = 'bosnian',
    botswana = 'botswana',
    hindu = 'hindu',
    honduran = 'honduran',
    malian = 'malian',
    vermont = 'vermont',
    montenegro = 'montenegro',
    tajikistani = 'tajikistani',
    talmud = 'talmud',
    mozambican = 'mozambican',
    mauritanian = 'mauritanian',
    kurdish = 'kurdish',
    corsican = 'corsican',
    tamilan = 'tamilan',
    chinese = 'chinese',
    portuguese = 'portuguese',
    gaelic = 'gaelic',
    bulgarian = 'bulgarian',
    bahamian = 'bahamian',
    philippine = 'philippine',
    libyan = 'libyan',
    navajo = 'navajo',
    sardinian = 'sardinian',
    hasidic = 'hasidic',
    basotho = 'basotho',
    kyrgyzstani = 'kyrgyzstani',
    berber = 'berber',
    bhutanese = 'bhutanese',
    east_asian = 'east_asian',
    slovenian = 'slovenian',
    solomon_islander = 'solomon_islander',
    finnish = 'finnish',
    luxembourgish = 'luxembourgish',
    norwegian = 'norwegian',
    omani = 'omani',
    pakistani = 'pakistani',
    liberian = 'liberian',
    laotian = 'laotian',
    sicilian = 'sicilian',
    hungarian = 'hungarian',
    macedonian = 'macedonian',
    lebanese = 'lebanese',
    lesotho = 'lesotho',
    samoan = 'samoan',
}

/**
 * FontPattern
 * @desc Enumeration type representing supported font patterns
 */
export enum FontPattern {
    default = 'default',
    audiowide = 'audiowide',
    balthazar = 'balthazar',
    bangers = 'bangers',
    baumans = 'baumans',
    bellota = 'bellota',
    bilbo = 'bilbo',
    bonbon = 'bonbon',
    carter_one = 'carter-one',
    caveat = 'caveat',
    chicle = 'chicle',
    chilanka = 'chilanka',
    coiny = 'coiny',
    cookie = 'cookie',
    damion = 'damion',
    delius = 'delius',
    italianno = 'italianno',
    devonshire = 'devonshire',
    butterfly_kids = 'butterfly-kids',
    bilbo_wash_caps = 'bilbo-swash-caps',
    beth_ellen = 'beth-ellen',
    julee = 'julee',
    lacquer = 'lacquer',
    lily_script_one = 'lily-script-one',
    architects_daughter = 'architects-daughter',
    annie_use_your_telescope = 'annie-use-your-telescope',
    amita = 'amita',
    comfortaa = 'comfortaa',
    monserrat_700 = 'monserrat-700',
    monserrat = 'monserrat',
    lobster = 'lobster',
    merienda = 'merienda',
    macondo = 'macondo',
    mansalva = 'mansalva',
    meddon = 'meddon',
    miltonian_tattoo = 'miltonian-tattoo',
    miniver = 'miniver',
    mogra = 'mogra',
    montez = 'montez',
    oregano = 'oregano',
    paprika = 'paprika',
    quando = 'quando',
    quintessential = 'quintessential',
    ramaraja = 'ramaraja',
    rancho = 'rancho',
    redressed = 'redressed',
    risque = 'risque',
    rochester = 'rochester',
    sail = 'sail',
    salsa = 'salsa',
    shrikhand = 'shrikhand',
    simonetta = 'simonetta',
    sniglet = 'sniglet',
    sofia = 'sofia',
    srisakdi = 'srisakdi',
    stylish = 'stylish',
    tillana = 'tillana',
    unkempt = 'unkempt',
    vibur = 'vibur',
    yesteryear = 'yesteryear',
}

/**
 * LayoutPattern
 * @desc Enumeration type representing supported layout patterns
 */
export enum LayoutPattern {
    default = 'default',
    socrates = 'socrates',
    churchill = 'churchill',
    samuel = 'samuel',
    zues = 'zues',
    pluto = 'pluto',
    sophocles = 'sophocles',
}

/**
 * AnimationPattern
 * @desc Enumeration type representing supported animation patterns
 */
export enum AnimationPattern {
    default = 'default',
    grow_out_in = 'grow-out-in',
}

/**
 * ThemePattern
 * @desc Enumeration type representing supported theme patterns
 */
export enum ThemePattern {
    default = 'default',
    default_repocard = 'default-repocard',
    dark = 'dark',
    radical = 'radical',
    merko = 'merko',
    gruvbox = 'gruvbox',
    tokyonight = 'tokyonight',
    onedark = 'onedark',
    cobalt = 'cobalt',
    synthwave = 'synthwave',
    highcontrast = 'highcontrast',
    dracula = 'dracula',
    prussian = 'prussian',
    monokai = 'monokai',
    vue = 'vue',
    vue_dark = 'vue-dark',
    shades_of_purple = 'shades-of-purple',
    nightowl = 'nightowl',
    buefy = 'buefy',
    blue_green = 'blue-green',
    algolia = 'algolia',
    great_gatsby = 'great-gatsby',
    darcula = 'darcula',
    bear = 'bear',
    solarized_dark = 'solarized-dark',
    solarized_light = 'solarized-light',
    chartreuse_dark = 'chartreuse-dark',
    nord = 'nord',
    gotham = 'gotham',
    material_palenight = 'material-palenight',
    graywhite = 'graywhite',
    vision_friendly_dark = 'vision-friendly-dark',
    ayu_mirage = 'ayu-mirage',
    midnight_purple = 'midnight-purple',
    calm = 'calm',
    flag_india = 'flag-india',
    omni = 'omni',
    react = 'react',
    jolly = 'jolly',
    maroongold = 'maroongold',
    yeblu = 'yeblu',
    blueberry = 'blueberry',
    slateorange = 'slateorange',
    kacho_ga = 'kacho-ga',
    arabesque = 'arabesque',
}

/**
 * RoutePattern
 * @desc Enumeration type representing supported route patterns
 */
export enum RoutePattern {
    default = 'default',
}
