apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: secure
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/instance: styled-proverbs
    app.kubernetes.io/version: '0.0.0'
    app.kubernetes.io/component: function
    app.kubernetes.io/part-of: serverless
    app.kubernetes.io/managed-by: tilt

spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - name: http
      port: 3000
      protocol: TCP
      targetPort: http
    - name: https
      port: 443
      protocol: TCP
      targetPort: https
