apiVersion: v1
kind: Service
metadata:
  name: styled-proverbs
  labels:
    app.kubernetes.io/name: styled-proverbs
    app.kubernetes.io/instance: styled-proverbs
    app.kubernetes.io/version: "0.0.0"
    app.kubernetes.io/component: function
    app.kubernetes.io/part-of: serverless
    app.kubernetes.io/managed-by: tilt

spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
  clusterIP: None
  selector:
    app: styled-proverbs
