name: Validate JSONs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  verify-json-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      # ls -1 -d "$PWD/data/"* | grep -v schemas | grep -v / | sed 's/$/, /g' | xargs echo | sed 's/,$//g'
      # ls -p ./data | grep -v / | tr '\n' ','
      # ls -1p | grep -v / | sed 's/$/, /g' | xargs echo | sed 's/,$//g'
      - name: Create JSONs list
        id: json_data
        run: echo "::set-output name=content::$(ls -1 -d "$PWD/data/"* | grep -v schemas | sed 's/$/, /g' | xargs echo | sed 's/,$//g')"

      - name: Validate JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: ./data/schemas/schema.json
          INPUT_JSONS: ${{ steps.json_data.outputs.content }}
