name: Process JSON fields

on:
  push:
    paths:
      - 'data/**.json'

jobs:
  process-json-fields:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1

      - name: Pull changeset
        run: git pull origin master

      - name: Process JSON fields
        uses: alexrogalskiy/github-action-json-fields@master
        id: process_json
        env:
          target_path: ./data
          fields: 'text'
        with:
          sourceData: .github/workflows/sourceData.json
          mode: 'unique'
          jsonFields: "${{ env.fields }}"
          targetPath: "${{ env.target_path }}"

      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        if: "steps.process_json.outputs.changed"
        with:
          commit_message: Add processed JSON files
          commit_options: '--no-verify --signoff'
