name: Process JSON fields

on:
  push:
    paths:
      - 'data/**.json'

jobs:
  process-json-fields:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v1

      - id: file_changes
        if: "!contains(github.event.head_commit.message, 'SKIP JSON SCRIPTS')"
        uses: trilom/file-changes-action@v1.2.3
        with:
          output: ','
          fileOutput: ','

      - name: Changed files
        if: "!contains(github.event.head_commit.message, 'SKIP JSON SCRIPTS')"
        run: |
          echo 'Files: ${{ steps.file_changes.outputs.files}}'
          echo 'Files modified: ${{ steps.file_changes.outputs.files_modified}}'
          echo 'Files added: ${{ steps.file_changes.outputs.files_added}}'
          echo 'Files removed: ${{ steps.file_changes.outputs.files_removed}}'

      - name: Generate JSON changelog
        if: "!contains(github.event.head_commit.message, 'SKIP JSON SCRIPTS')"
        id: generate_json
        run: node ./.github/workflows/sourceData.js "${{ steps.file_changes.outputs.files }}"

      - name: Set json source file
        id: json-source-file
        run: |
          if [[ "${{ github.event.head_commit.message }}" == *"SKIP JSON SCRIPTS"* ]]; then
              sourceFile=".github/workflows/sourceData.json"
            else
              sourceFile="${{ runner.temp }}/sourceData.json"
          fi

          echo $sourceFile
          echo "::set-output name=sourceFile::$sourceFile"

      - name: Process JSON changelog fields
        uses: alexrogalskiy/github-action-json-fields@master
        id: process_json
        env:
          source_data: "${{ steps.json-source-file.outputs.sourceFile }}"
          target_path: './data'
          json_fields: 'text'
          mode: 'unique'
        with:
          mode: "${{ env.mode }}"
          jsonFields: "${{ env.json_fields }}"
          sourceData: "${{ env.source_data }}"
          targetPath: "${{ env.target_path }}"

      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        if: "steps.process_json.outputs.changed"
        with:
          commit_message: Add processed JSON files
          commit_options: '--no-verify --signoff'
