name: Process JSON files by unique fields

on:
  push:
    paths:
      - '.github/workflows/json_unique.yml'
      - 'data/**.json'

jobs:
  process-json-unique:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      max-parallel: 1
      matrix:
        include:
          - file: afghan_proverbs.json
            property: '$.afghan[*]'
          - file: african_proverbs.json
            property: '$.african[*]'
          - file: albanian_proverbs.json
            property: '$.albanian[*]'

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1

      - name: Pull changeset
        run: |
          git pull origin master

      - id: file_changes
        uses: trilom/file-changes-action@v1.2.3
        with:
          output: ','
          fileOutput: ','

      - name: Process JSON file by fields
        uses: alexrogalskiy/github-action-json-fields@master
        if: "contains(steps.file_changes.outputs.files, ${{ matrix.file }})"
        id: process_json
        env:
          target_path: ./data
          fields: 'text'
        with:
          mode: 'unique'
          jsonPath: "${{ matrix.property }}"
          jsonFields: "${{ env.fields }}"
          sourceFile: "${{ env.target_path }}/${{ matrix.file }}"
          targetPath: "${{ env.target_path }}"
          targetFile: "${{ matrix.file }}"

      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        if: "steps.process_json.outputs.changed"
        with:
          commit_message: Add processed JSON files
          commit_options: '--no-verify --signoff'
