name: Process JSON fields

on:
  push:
    paths:
      - 'data/**.json'

jobs:
  process-json-fields:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1

      - id: file_changes
        uses: trilom/file-changes-action@v1.2.4
        with:
          output: ','
          fileOutput: ','

      - name: Changed files
        run: |
          echo 'Files: ${{ steps.file_changes.outputs.files}}'
          echo 'Files modified: ${{ steps.file_changes.outputs.files_modified}}'
          echo 'Files added: ${{ steps.file_changes.outputs.files_added}}'
          echo 'Files removed: ${{ steps.file_changes.outputs.files_removed}}'

      - name: Generate JSON changelog
        id: generate_json
        run: node ./.github/workflows/sourceData.js "${{ steps.file_changes.outputs.files }}"

      - name: Process JSON changelog fields
        uses: alexrogalskiy/github-action-json-fields@master
        id: process_json
        env:
          target_file: "${{ runner.temp }}/sourceData.json"
          target_path: ./data
          fields: 'text'
        with:
          sourceData: "${{ env.target_file }}"
          mode: 'unique'
          jsonFields: "${{ env.fields }}"
          targetPath: "${{ env.target_path }}"

      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        if: "steps.process_json.outputs.changed"
        with:
          commit_message: Add processed JSON files
          commit_options: '--no-verify --signoff'
