name: Validate JSONs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  verify-json-validation:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4

      - name: Create JSONs list
        id: json_data
        run: |
          echo "::set-output name=files::$(find -L ./data -type f | grep -v schemas | sed -e 's#$##' | head -c -1 | tr '\n' ',')"

      - name: Validate JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: ./data/schemas/schema.json
          INPUT_JSONS: ${{ steps.json_data.outputs.files }}
