name: Verify Docs

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  verify-docs:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '*'
          check-latest: true

      - name: Install core dependencies
        run: npm install --no-audit

      - name: Generate docs
        run: npm run docs

      - name: Check for changes
        run: |
          if [ -z "$(git status --porcelain)" ]; then
            echo "No changes to docs files detected"
          else
            echo "Changes to docs files detected, please run 'npm run docs' to sync docs"
            exit 1
          fi
